### PR TITLE
Address Katie's get_genotype_vcf.py issue (#71)

### PR DESCRIPTION
**Pull request by annacuomo**
Addressing @katiedelange's comments from https://github.com/populationgenomics/saige-tenk10k/issues/71

* LD pruning parameters as arguments
* pruning and downsampling approach described in the README
* exclude X,Y,MT chroms from VRE genotype file, and update README
* only subset (to 1%)  if necessary 
* reduce checkpoints (see discussion below), leaving only the one post subsetting and pre-pruning, since the subsetting may make the re-partitioning less than ideal, and the pruning is an expensive operation that doesn't do much internal checkpointing.

@katiedelange ready for you to review!
@MattWellie thanks for the comments below re: checkpoints 🙏

### CODE REVIEW

**Comment by MattWellie** [comment]
My gut feeling is that there are probably too many checkpoints in here at the moment. Each checkpoint writes the full MT/VDS out to disc, which is expensive & time consuming, as well as costing $ until it's deleted. Between the changes you're making you have 3 separate checkpoints, I'd try reducing that to just 1, probably just after the subsetting. From memory it was important to checkpoint just before running the LD-pruning method, as that doesn't do any checkpointing, but does add a lot of computational steps, so it's prone to running out of memory.

You might also want to consider your use of `checkpoint_mt` - I would advise forcing a new checkpoint each time. If you run this twice, and change the settings in between (e.g. relateds_to_drop_path), the run will detect the first checkpoint, read it in, and continue from there. By continuing from a previous checkpoint you're not exactly sure what you're continuing from... checkpoint_mt does a lot of resuming which might have been good for iterative development, but IMO it's much safer to always overwrite the previous checkpoint.

... an alternative is to include all the settings into the checkpoint name (maybe as a hash), so that when you resume from a checkpoint you resume from a previous run which was using the exact same settings, but that's probably a bit of a hassle

**Comment by MattWellie** [comment]
Unrelated, it looks like this could create a bias towards the start of the genome:
https://github.com/populationgenomics/saige-tenk10k/blob/5931504572a76c12272f924ecc3bcae1f3ba8b2c/get_genotype_vcf.py#L388-L390

"subsample all variants based on a ratio of `n * 1.1`, then choose the first `n` rows"

I vaguely remember this being developed, but I don't remember the importance of the 1.1, or whether a slight regional bias would be important

**Comment by annacuomo** [comment]
> Unrelated, it looks like this could create a bias towards the start of the genome:
> 
> https://github.com/populationgenomics/saige-tenk10k/blob/5931504572a76c12272f924ecc3bcae1f3ba8b2c/get_genotype_vcf.py#L388-L390
> 
> "subsample all variants based on a ratio of `n * 1.1`, then choose the first `n` rows"
> 
> I vaguely remember this being developed, but I don't remember the importance of the 1.1, or whether a slight regional bias would be important

So ideally here I'd just sample `n` exact variants but the `sample_rows` requires a portion instead (between 0 and 1). Because I wanted exactly `n` and that ratio may be just under I am multiplying but slightly more to make sure I get at least `n`, and then take the head. Any cleaner solutions would be more than welcome, but also a slight regional bias would not be problematic at all here imo!

**Comment by annacuomo** [comment]
> My gut feeling is that there are probably too many checkpoints in here at the moment. Each checkpoint writes the full MT/VDS out to disc, which is expensive & time consuming, as well as costing $ until it's deleted. Between the changes you're making you have 3 separate checkpoints, I'd try reducing that to just 1, probably just after the subsetting. From memory it was important to checkpoint just before running the LD-pruning method, as that doesn't do any checkpointing, but does add a lot of computational steps, so it's prone to running out of memory.
> 
> You might also want to consider your use of `checkpoint_mt` - I would advise forcing a new checkpoint each time. If you run this twice, and change the settings in between (e.g. relateds_to_drop_path), the run will detect the first checkpoint, read it in, and continue from there. By continuing from a previous checkpoint you're not exactly sure what you're continuing from... checkpoint_mt does a lot of resuming which might have been good for iterative development, but IMO it's much safer to always overwrite the previous checkpoint.
> 
> ... an alternative is to include all the settings into the checkpoint name (maybe as a hash), so that when you resume from a checkpoint you resume from a previous run which was using the exact same settings, but that's probably a bit of a hassle

Hi @MattWellie thanks, I can't say I remember making that `checkpoint_mt` method, so apologies if I didn't appreciate how it was mostly for development! I have commented out most checkpoints now, only leaving the one before LD pruning, and commented out any use of `checkpoint_mt` as well. Could you check whether this is what you meant, and if so I'll go ahead and delete those lines instead! Thank you!

**Comment by MattWellie** [comment]
> I can't say I remember making that `checkpoint_mt` method, and I still don't fully get it

I think I may have written it 😆 

It does 2 things - 
- creates a checkpoint
- writes a second checkpoint with repartitioned data

The repartitioning was inspired by problems I was running into in the RD pipeline - each separate shard of data is processed in parallel, if you have too many partitions, hail has to manage a lot of overhead organising all the jobs. If you have too few partitions, you don't get the benefits of parallel processing and the VM can run out of resources.

The issue it aims to solve is the content of each partition - if you start with well partitioned data (each partition has a roughly equal data content), then you apply a number of filters, this can unbalance your partitions - some being empty, some remaining full. As a specific example, when you down sample your data to 1%, the partition counts are unchanged, so you are making your partitions 99% more sparse. In this situation you probably want to run your down sampling, then repartition, so that instead of creating a huge number of VMs, each processing a trivial number of variants, you make a much smaller number of VMs, each doing a meaningful amount of computation.

Sorry if that's a bit of a ramble, but that's what this method was aiming to achieve. I think that's still reasonable based on this being a progressive filtering process, where repartitioning should give you meaningful improvements downstream (whether that's faster runtime, or just a process that succeeds instead of failing).

The bit I'm more concerned about is the detection of previous checkpoints, and resuming from them. If you only plan to run this once, or you only plan to run it with one set of settings, then don't worry about it.

If you're likely to run this more than once, you can run into an issue where you run once with a given set of settings/samples to keep/thresholds, then a subsequent run with different settings will continue from those checkpoints instead of writing new ones - if this script in its current form is run with different settings, it's hard to be confident about the data you're using.

Removing the read-existing-checkpoint behaviour, or always calling `checkpoint_mt` with `force=True` would solve this

**Comment by annacuomo** [comment]
> > I can't say I remember making that `checkpoint_mt` method, and I still don't fully get it
> 
> I think I may have written it 😆
> 
> It does 2 things -
> 
> * creates a checkpoint
> * writes a second checkpoint with repartitioned data
> 
> The repartitioning was inspired by problems I was running into in the RD pipeline - each separate shard of data is processed in parallel, if you have too many partitions, hail has to manage a lot of overhead organising all the jobs. If you have too few partitions, you don't get the benefits of parallel processing and the VM can run out of resources.
> 
> The issue it aims to solve is the content of each partition - if you start with well partitioned data (each partition has a roughly equal data content), then you apply a number of filters, this can unbalance your partitions - some being empty, some remaining full. As a specific example, when you down sample your data to 1%, the partition counts are unchanged, so you are making your partitions 99% more sparse. In this situation you probably want to run your down sampling, then repartition, so that instead of creating a huge number of VMs, each processing a trivial number of variants, you make a much smaller number of VMs, each doing a meaningful amount of computation.
> 
> Sorry if that's a bit of a ramble, but that's what this method was aiming to achieve. I think that's still reasonable based on this being a progressive filtering process, where repartitioning should give you meaningful improvements downstream (whether that's faster runtime, or just a process that succeeds instead of failing).
> 
> The bit I'm more concerned about is the detection of previous checkpoints, and resuming from them. If you only plan to run this once, or you only plan to run it with one set of settings, then don't worry about it.
> 
> If you're likely to run this more than once, you can run into an issue where you run once with a given set of settings/samples to keep/thresholds, then a subsequent run with different settings will continue from those checkpoints instead of writing new ones - if this script in its current form is run with different settings, it's hard to be confident about the data you're using.
> 
> Removing the read-existing-checkpoint behaviour, or always calling `checkpoint_mt` with `force=True` would solve this

Great thanks for your help! If you have time can you review this PR from your perspective?

**Review by katiedelange — APPROVED** [review]
Looks good from my perspective, thanks for making those changes @annacuomo.

**Pull request merged**
